name: live-shots

on:
  # Run every 6 hours (13 min past the hour to avoid the top-of-hour rush)
  schedule:
    - cron: "13 */6 * * *"
  # Allow manual runs from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  shot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .

      - name: Fire cross-provider live shot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python -m anomaly_scanner.cross_probe \
            --providers openai,anthropic \
            --runs 3 \
            --temperature 0.9 \
            --threshold 0.85 \
            --prompt "Explain the purpose of AnomalyScope in one concise sentence."

      - name: Refresh homepage index (mirrors LATEST_ANOMALY.md)
        run: |
          python scripts/update_index.py

      - name: Commit & push artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.md docs/LATEST_ANOMALY.md docs/anomalies || true
          git commit -m "ci: publish live anomaly and update homepage [skip ci]" || echo "nothing to commit"
          git push
